services:
  - type: web
    name: reel-match
    env: python
    region: oregon
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app